---
site_name: Gran Turismo 7 Telemetry
site_url: https://www.sommerfeld.io
site_author: Sebastian Sommerfeld
site_description: >-
  Gran Turismo 7 Telemetry Dashboard

repo_name: sommerfeld-io/gt-telemetry
repo_url: https://github.com/sommerfeld-io/gt-telemetry

copyright: Copyright &copy; 2024 Sommerfeld.io

docs_dir: docs
site_dir: target/docs/site

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - content.code.copy
    - content.tabs.link
    # - navigation.tabs
    - navigation.footer
    # - navigation.sections
    # - navigation.expand
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - kroki:
  - search:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sommerfeld-io/gt-telemetry
    # - icon: fontawesome/brands/docker
    #   link: https://hub.docker.com/u/sommerfeldio

nav:
  - Getting Started: index.md
  - About this Project:
      - about/development-guide.md
      - about/contribute.md
      - about/security.md
      - about/code-of-conduct.md
      - about/license.md
  - about/terms.md
